name:                parquet-hs
version:             0.1.0.0
github:              "winkduo/parquet-hs"
license:             BSD3
author:              "Yigit Ozkavci"
maintainer:          "yigitozkavci8@gmail.com"
copyright:           "2019 Yigit Ozkavci"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/parquet-hs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:         src
  ghc-options:         -Wall
  dependencies:
  - pinch
  - text
  - bytestring
  - binary
  - pretty-simple
  - error-util
  - mtl
  - containers
  - conduit
  - binary-conduit
  - monad-logger
  - conduit-extra
  - generic-lens
  - microlens

tests:
  parquet-hs-test:
    main: Spec.hs
    type: exitcode-stdio-1.0
    source-dirs: tests
    dependencies:
    - parquet-hs
    - hspec
    - QuickCheck
    - bytestring
    - binary
